version: "3"
services:
  web1:
    image: sample-web
    build:
      context: ./Sample.Web
      dockerfile: win.dockerfile
    depends_on:
      - sql
    networks:
      - snet
    healthcheck:
      test: [ "CMD", "curl", "-l", "http://localhost:80" ]
      interval: 1m
      retries: 3

  web2:
    image: sample-web
    depends_on:
      - sql
    networks:
      - snet
    healthcheck:
      test: [ "CMD", "curl", "-l", "http://localhost:80" ]
      interval: 1m
      retries: 3

  lb:
    image: nginx-nanoserver
    build:
      context: .
      dockerfile: nginx.dockerfile
    depends_on:
      - web1
      - web2
    ports:
      - 8080:80
    networks:
      - snet

  sql:
    image: microsoft/mssql-server-windows-developer
    environment:
      - SA_PASSWORD=Password1 
      - ACCEPT_EULA=Y
    volumes:
      - ./mssql:C:/temp
    ports:
      - "1433:1433"
    networks:
      - snet
    healthcheck:
      test: [ "CMD", "sqlcmd", "-U", "sa", "-P", "Password1", "-Q", "select 1" ]
      interval: 1m
      retries: 3

# default required for bug in windows containers on older versions.
networks:
  default:
    external:
      name: nat
  snet:
    driver: nat